### PR TITLE
Add reverse option in config file

### PR DESCRIPTION
**Pull request by SrideviRamesh**
This commit moves reverse boolean argument in config file.

Tested the changes successfully.

### CODE REVIEW

**Review by RameshIyyar — COMMENTED** [review]
Thanks for the patch..could you please use config for the extensions as well in the same commit or different commit in the same PR?

**Comment by SrideviRamesh** [comment]
> Thanks for the patch..could you please use config for the extensions as well in the same commit or different commit in the same PR?

Ohh right, we have extensions as well. Ok I will try to fit it in this commit.

**Comment by SrideviRamesh** [comment]
> > Thanks for the patch..could you please use config for the extensions as well in the same commit or different commit in the same PR?
> 
> Ohh right, we have extensions as well. Ok I will try to fit it in this commit.

Looks like args.extension is consumed in many places. I will push separate commit for it.

**Comment by RameshIyyar** [comment]
> > > Thanks for the patch..could you please use config for the extensions as well in the same commit or different commit in the same PR?
> > 
> > 
> > Ohh right, we have extensions as well. Ok I will try to fit it in this commit.
> 
> Looks like args.extension is consumed in many places. I will push separate commit for it.

OK you could push in the separate PR.

**Review by RameshIyyar — APPROVED** [review]

**Review by harsh-agarwal1 — APPROVED** [review]

**Review by spinler — APPROVED** [review]

**Pull request merged**
